### ISSUE TITLE
minigame

### ISSUE THREAD

**Issue by YellowAfro** [Unbewohnte/AlbionFisherBot#3]
Hi ,everything works great , just one problem, the  bot sometimes loses to the minigame because its fast game  , is there a fix for that or i just have to wait for an easy catch?

**Comment by Unbewohnte** [comment]
You can change "time.sleep()" here after "if". I have chosen the optimal value. If you are fishing in the high level area you definitely need to change it
![image](https://user-images.githubusercontent.com/65883674/84415209-1b47b480-ac1b-11ea-91db-0b2d7b10971e.png)
Good luck !
